# Generated by Django 5.2 on 2025-04-16 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'ожидает'), ('accepted', 'принята'), ('canceled', 'отменена')], default='waiting', verbose_name='Status')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='Comment')),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='ad.ad', verbose_name='Ads')),
            ],
        ),
    ]
