# Generated by Django 5.2 on 2025-04-17 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_proposal', '0003_rename_ad_id_exchangeproposal_ad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeproposal',
            options={'ordering': ['id'], 'verbose_name': 'ExchangeProposal'},
        ),
        migrations.AlterModelTable(
            name='exchangeproposal',
            table='ExchangeProposal',
        ),
    ]
