# Generated by Django 5.2 on 2025-04-16 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Discription')),
                ('image_url', models.CharField(blank=True, max_length=200, verbose_name='Image_url')),
                ('condition', models.CharField(max_length=200, verbose_name='Condition')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='category.category', verbose_name='Category')),
            ],
        ),
    ]
