# Generated by Django 5.2 on 2025-04-16 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
