# Generated by Django 5.2 on 2025-04-17 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_rename_category_id_ad_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['id'], 'verbose_name': 'Ad'},
        ),
        migrations.AlterModelTable(
            name='ad',
            table='Ad',
        ),
    ]
