# Generated by Django 5.2 on 2025-04-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_alter_ad_options_alter_ad_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='condition',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Discription'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Image_url'),
        ),
    ]
